# Generated by Django 4.2.4 on 2023-09-08 18:13

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tb_Registros',
            fields=[
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('id_ocorrencia', models.AutoField(primary_key=True, serialize=False)),
                ('Usuário', models.CharField(max_length=45)),
                ('Data da Ocorrência', models.DateField(help_text='Data em que foi visualizada a praga.')),
                ('relato', models.CharField(choices=[('Formiga-rapa-rapa', 'Formiga-rapa-rapa'), ('Mancha-circular', 'Mancha-circular'), ('Larva-arame', 'Larva-arame')], help_text='Selecione qual o tipo de praga esta contaminando.', max_length=40)),
                ('Cultura', models.CharField(choices=[('Milho', 'MILHO'), ('Arroz', 'ARROZ'), ('Soja', 'SOJA')], help_text='Qual plantação foi contaminada?', max_length=45)),
                ('status', models.CharField(choices=[('s', 'Sim'), ('N', 'Não')], help_text='A praga esta controlada?', max_length=45, verbose_name='Controlada?')),
                ('Nome da Propriedade afetada', models.CharField(help_text='Nome da propriedade que esta sendo contaminada.', max_length=60)),
                ('Total do prejuizo R$', models.DecimalField(decimal_places=2, default=0.0, help_text='qual o valor do prejuizo?', max_digits=20)),
                ('Quantidade de hectar afetado', models.IntegerField(default=0, help_text='quantos hectares estão contaminados')),
                ('latitude', models.CharField(max_length=45)),
                ('longitude', models.CharField(max_length=45)),
                ('imagem', stdimage.models.StdImageField(blank=True, force_min_size=False, help_text='Selecione as imagens da praga.', null=True, upload_to='images', variations={}, verbose_name='Imagem')),
                ('Observações', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tabela de Registro',
                'verbose_name_plural': 'Tabela de Registros',
            },
        ),
        migrations.CreateModel(
            name='TbPragas',
            fields=[
                ('id_praga', models.AutoField(primary_key=True, serialize=False)),
                ('cultura', models.CharField(blank=True, max_length=45, null=True)),
                ('especie', models.CharField(blank=True, max_length=45, null=True)),
                ('nome_comum', models.CharField(max_length=45)),
                ('nome_comum2', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Tabela de Praga',
                'verbose_name_plural': 'Tabela de Pragas',
            },
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Tabela de Perfil', 'verbose_name_plural': 'Tabela de Perfis'},
        ),
    ]
